# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sampledevops2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://pkcontainer2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_045269ae73e74f1bbe2bbabb34f9b06a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9c01d2033ed14482bfb51770f6db9334 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_045269ae73e74f1bbe2bbabb34f9b06a }}/sampledevops2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sampledevops2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_977425bc831249768197fec3a75e48c7 }}
        images: 'pkcontainer2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_045269ae73e74f1bbe2bbabb34f9b06a }}/sampledevops2:${{ github.sha }}'