# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pkdockerdemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://pkcontainer2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2c5dd5db264c4078a48ad970256ebfb0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_250ecb7df94549da8fe0fbf550e8a6c5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_2c5dd5db264c4078a48ad970256ebfb0 }}/SampleDevOps2:${{ github.sha }}
        file: ./SampleDevOps2/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pkdockerdemo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a585422ee9ac48928481c7d62efcc766 }}
        images: 'pkcontainer2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2c5dd5db264c4078a48ad970256ebfb0 }}/
        
        :${{ github.sha }}'
